### ISSUE TITLE
Remove conda dependency?

### ISSUE THREAD

**Issue by gusbeane** [showyourwork/showyourwork#114]
Is it possible to remove the conda dependency? I really dislike conda (slow, messes with other python installations). I tried pip installing conda in a virtual environment, but got the following error

```
ERROR: The install method you used for conda--probably either `pip install conda`
or `easy_install conda`--is not compatible with using conda as an application.
If your intention is to install conda as a standalone application, currently
supported install methods include the Anaconda installer and the miniconda
installer.  You can download the miniconda installer from
https://conda.io/miniconda.html.


Conda package manager not found. Is it installed and available in the system PATH?
```

**Comment by rodluger** [comment]
Not really, at least not for the current implementation. ``showyourwork`` is built on top of Snakemake, which makes heavy use of ``conda`` environments to isolate different build steps. It's also the easiest way to get things like ``tectonic`` installed.

I would also love to move past ``conda`` environments and on to something like Docker containers to maximally ensure reproducibility and dependency management. But to be honest I probably won't have the time to implement something like that in the foreseeable future.

**Comment by gusbeane** [comment]
fair enough!

**Comment by MilesCranmer** [comment]
Easiest fix to get improved speed would be to use [mamba](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html) instead of conda, which is a faster rewrite. It uses all the same registries/packages. From their docs:

> mamba is a drop-in replacement and uses the same commands and configuration options as conda. You can swap almost all commands between conda & mamba.

That being said, docker support would be great to have–you could set up the conda environment inside a docker container, there shouldn't be too many changes. Would help keep things separate from user environments!
