### ISSUE TITLE
cache publishing issues

### ISSUE THREAD

**Issue by mathren** [showyourwork/showyourwork#117]
Hi Rodrigo,

I have a showyourwork with [public static dataset](https://zenodo.org/record/6600641) and a [cache](https://sandbox.zenodo.org/record/1074085) that are both public (repo isn't yet). Both locally and on github actions the pdf is successfully compiled *but* showyourwork is not putting the dataset links in the figure, e.g.:

![image](https://user-images.githubusercontent.com/49067756/175993884-347a4cec-2616-4442-8785-c5003da18fe5.png)

Moreover, despite having both the ZENODO_TOKEN and SANDBOX_TOKEN defined (and passed as secrets to the repo), `showyourwork cache publish` fails with an error 403 (while `create` and `freeze` worked fine). When I ran `showyourwork cache freeze` the sandbox repository went from `draft` to `published` on sandbox.zenodo.

**Comment by rodluger** [comment]
Currently, showyourwork only adds the Zenodo link if the Zenodo dataset is a *direct* dependency of the figure. In your workflow, there's an intermediate step (the unzipping rule) between the dataset and the figure script, so the icon isn't added automatically. I can change the behavior of showyourwork to do what you expect in this case, though -- shouldn't be too hard.

**Comment by rodluger** [comment]
Hey @mathren I fixed this as well. Can you try running your workflow again without making the dataset dependency of the figure explicit? In other words, I believe you have a Zenodo dataset `A` that gets unzipped in a custom rule to a file `B`, and `B` is marked as a dependency of your figure. Previously, this would **not** give you a Zenodo icon next to the figure, since the dependency of the figure on `A` was implicit. The current version on the `main` branch fixes this behavior, and it should infer the upstream dependency and give you an icon. Let me know if it works!

**Comment by mathren** [comment]
mmh, that does not seem to work for me. using `0.3.1.dev16+ga77bd0a` I get the same behavior as before.
Also, I've noticed that the hyperlinks in the  icons of the pdf compiled by arXiv (from the showyourwork-generated tarball) are broken (possibly same/similar bug as the naming of the cache on zenodo).

For example, the github link for fig. 1 in [this paper](https://arxiv.org/pdf/2206.15338.pdf) should be `https://github.com/mathren/CE_accretors/blob/844cf5fc95e4385cb012462aa336826908de5376/src/scripts/HRD.py` (has correctly linked on the version compiled by github actions) and it is instead `https://arxiv.org/pdf/git@github.com:mathren/CE_accretors/blob/975717fece1bbb3bccfbae0d5b57e748743cb9ad/src/scripts/HRD.py`

**Comment by rodluger** [comment]
Ok, I'll keep working on it then. Thanks for testing it. As for your other issue with the broken links, I've moved it to #125 .

**Comment by rodluger** [comment]
@mathren I created a test repository to properly test all this, and it works as expected for me. The exact commit I'm talking about is [here](https://github.com/showyourwork/showyourwork-example/tree/b8fb5be6b72601f35b63ff9dc16f41f2c9b1b107).

I have two figures, `figure1.pdf` and `figure2.pdf`. The first one depends on a dataset `B.dat`, which gets generated from a dataset `A.dat`, which in turn gets downloaded from Zenodo. In the [config](https://github.com/showyourwork/showyourwork-example/blob/b8fb5be6b72601f35b63ff9dc16f41f2c9b1b107/showyourwork.yml), I only mark `B.dat` as an explicit dependency of the figure script. 

The second figure depends on a dataset `D.dat`, which gets generated from a dataset `C.dat`. The latter is the output of a rule in the [Snakefile](https://github.com/showyourwork/showyourwork-example/blob/b8fb5be6b72601f35b63ff9dc16f41f2c9b1b107/Snakefile), which is cached on Zenodo Sandbox. Again, I only mark `D.dat` as an explicit dependency of the figure script.

When `showyourwork` builds the [PDF](https://github.com/showyourwork/showyourwork-example/blob/main-pdf/ms.pdf), it infers the correct upstream dependencies, generating the expected margin icons:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/9323819/178773355-fedf2078-2407-4076-b49e-e941a8be457b.png">

<img width="556" alt="image" src="https://user-images.githubusercontent.com/9323819/178773380-dfcb7c12-1d70-4df2-91b5-388d42b70800.png">

The dataset icon for Figure 2 is red, since it's in an unpublished Sandbox deposit (c.f. #113).

Here's the full article graph (set `render_dag: true` in the config):

<img width="799" alt="image" src="https://user-images.githubusercontent.com/9323819/178772156-2aada32e-cb99-4e56-8327-f4bd3b8876aa.png">

Note that the dependencies of the figures on `A.dat` and `C.dat` are implicit.

So I think the new feature is working as expected. Which repository are you having trouble with? I can poke around to try to debug.

**Comment by rodluger** [comment]
Actually there was one potential issue I found that has since been [fixed](https://github.com/showyourwork/showyourwork/commit/96e8aa8704f7fc4a0219b056edd1c8e740ffd02d#diff-49ad942a712a39273b50d911c4b52edc6413d404a2934f75de69b6ca53beb32f). No rush, but let me know if you get a chance to re-run this (base it on `main`).
