### ISSUE TITLE
[Feature] GitHub action `latexdiff` on pull requests

### ISSUE THREAD

**Issue by MilesCranmer** [showyourwork/showyourwork#123]
If you have two latex files, before and after a change, you can run:
```bash
latexdiff old.tex new.tex > diff.tex
```
This is another LaTeX file that one can render as a PDF. After building it, you will see that changes to the manuscript are underlined in red, and updated text is given in blue. Here is an example from the [CTAN page](https://ctan.math.utah.edu/ctan/tex-archive/support/latexdiff/doc/latexdiff-man.pdf):
![Screen Shot 2022-07-10 at 8 19 51 PM](https://user-images.githubusercontent.com/7593028/178168033-9fd52dd4-253a-4ba6-897a-67437b2bcfe7.png)

This is extremely useful for viewing changes to a paper.

I think it would be brilliant if the GitHub action that builds the PDF on a pull request, would also render the diff version of the PDF. That would be game changing for collaborative paper editing!

Cheers,
Miles

**Comment by MilesCranmer** [comment]
@rodluger I'd be happy to help add this one. Can you point me to the location of the YML file that defines the pull request bot?

Is it this one? https://github.com/showyourwork/showyourwork-action/blob/main/process-pull-request/action.yml Where could I add a preprocessing part before this action?

**Comment by rodluger** [comment]
Cool! I would probably build the PDF of the diff at this step of the main workflow build instead, since this is the workflow in which we install conda & showyourwork: https://github.com/showyourwork/showyourwork-action/blob/main/src/publish.js#L29

The bot step doesn't install/run anything -- it just downloads the artifact and pushes the PDF to a separate branch. Building the diff at that step would lead to unnecessary overhead I think. Instead, build it in the main branch and include it in the artifact, then have the bot download & push it.

The if statement on the line I highlighted checks if it's a PR build, so you could do this only for PRs. You could add something like

```javascript
// Build the diff
core.startGroup("Build article diff");
exec("latexdiff old.tex ms.tex > ms.tex");
exec("showyourwork build");
core.endGroup();
```

where ``old.tex`` is the previous version of the manuscript. You'd have to clone the tip of the base branch to get access to that, I think. The other wrinkle is that I'm only installing `tectonic` on GitHub Actions -- for `latexdiff` I think you need an actual TeXLive installation (unless you know of a standalone version).

**Comment by MilesCranmer** [comment]
Thanks!

I looked into this, and `latexdiff` seems to be nothing more than a Perl script: https://github.com/ftilmann/latexdiff/blob/master/latexdiff (also listed on CTAN here: https://ctan.org/pkg/latexdiff?lang=en). , So after adding Perl to the github action (if it wasn't already installed by tectonic), the individual latexdiff script can be executed without much issue.

**Comment by MilesCranmer** [comment]
Started a pull request here: https://github.com/showyourwork/showyourwork-action/pull/2

**Comment by MilesCranmer** [comment]
Closed on https://github.com/showyourwork/showyourwork-action/pull/2.
