### ISSUE TITLE
Compatibility with Tufte?

### ISSUE THREAD

**Issue by astrogewgaw** [showyourwork/showyourwork#133]
<div align="justify">

I was trying out `showyourwork` for a document I am working on (which can be found [**here**](https://github.com/astrogewgaw/whyjulia)) and I ran into a bit of trouble, since I am using the `tufte-handout` class (ref: [**here**](https://github.com/Tufte-LaTeX/tufte-latex)). I am guessing that both `showyourwork` and `tufte-handout` do stuff with the `\marginnote` command, which is why my document refuses to compile with this error:

```bash
error: marginnote.sty:323: LaTeX Error: Command \marginnote already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help
error: halted on potentially-recoverable error as specified

! LaTeX Error: Command \marginnote already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.323 }
       
No pages of output.
```

Is there a way to make both of them play along nicely?

**PS:**

1. Compiling the document itself with the command:
    
    ```bash
    tectonic -X compile src/tex/ms.tex -Z shell-escape
    ```
    
    works, probably because it skips all the `showyourwork` machinery.

2. I am also using `minted`, which relates to another issue (#132). The above error pops up when I comment out all the `minted` related stuff (which right now is just a couple of lines for the setup).

</div>

**Comment by rodluger** [comment]
Interesting, thanks for raising this. The `\marginnote` used by `showyourwork` is provided by the [package](https://ctan.org/pkg/marginnote?lang=en) of the same name. Looks like `tufte-handout` defines its own custom `\marginnote` command, which does not use the same `marginnote` package.

This makes `tufte-handout` fundamentally incompatible with `showyourwork`, unfortunately. Fixing this would require re-writing all of the machinery in `showyourwork` to handle margin icons, which I'm afraid I don't have time to do.

One thing you could try is to fork [github.com/Tufte-LaTeX/tufte-latex](github.com/Tufte-LaTeX/tufte-latex) and rename `\marginnote` [here](https://github.com/Tufte-LaTeX/tufte-latex/blob/efb8c8e836890bad71fb5834acdd316ebde6db12/tufte-common.def#L1087) to something else, like `\tuftemarginnote`, and use that in your document instead. That should work in principle, although it's possible the `marginnote` package will mess up some of the formatting imposed by `tufte-handout`. If you have time, would you mind giving that a shot and let me know if it works? You don't even have to fork the repo; just copy over the relevant style files to the `src/tex` directory and make the change I suggested above.

As for your second issue, yes, that will be fixed by #132, which I will hopefully get around to next week.

**Comment by astrogewgaw** [comment]
<div align="justify">

Hey 😀 ! I gave what you suggested a shot and it worked, but it had the exact caveat that you were afraid of: the `marginnote` package messed things up when I tested the whole thing with a plot generated via a script. As an aside, if someone modified `Tufte-LaTeX` to use `marginnote` instead of `marginpar` (which is what I think it currently uses, if I have read the code right), would it be able to work together with `showyourwork`? I doubt it will, but I thought I might as well ask you what you think 😅 . Since the document I am writing is more in the style of an essay than a scientific publication, I think I will just go back to a simpler setup for now. I am definitely going to use `showyourwork` in the future though, this is some really great stuff 😁 👍🏾 ! I am closing this issue for now, since the packages are just fundamentally incompatible, and the whole thing won't be easily fixed. Feel free to reopen this if that changes.

</div>

**Comment by rodluger** [comment]
Cool. I'm not sure whether marginnote vs. marginpar would be any better -- it depends on the inner workings of the showkeys package, which is what I'm actually using to show the icons (that package uses marginnote to display the equation and figure labels in the margin, and I'm overriding it to display icons instead). A simple test would be to create a standard Tex document with showkeys enabled and try to add additional, manual margin notes, and see if the formatting looks ok.

But yes, that's all somewhat beyond the scope of showyourwork right now. Happy to consider a PR though if anyone's willing to look into this!
