### ISSUE TITLE
Handling multiple labels exception

### ISSUE THREAD

**Issue by dfm** [showyourwork/showyourwork#145]
The Annual Reviews `documentclass` (#144) automatically inserts its own label into figures (I assume for table of contents reasons?) so we're getting the following error from showyourwork:

```
A figure has multiple labels: `fig:quasar, chk@figure@1`
```

Originating here:

https://github.com/showyourwork/showyourwork/blob/0c065b2dc5f74b9612ab064d6674b91e206404ce/showyourwork/workflow/scripts/preprocess.py#L210-L215

It's not obvious to me why we need to require only a single label. Would it be possible to soften this requirement?

**Comment by rodluger** [comment]
Interesting. The figure label currently needs to be unique because it is the [key in the dictionary](https://github.com/showyourwork/showyourwork/blob/0c065b2dc5f74b9612ab064d6674b91e206404ce/showyourwork/workflow/scripts/preprocess.py#L417) mapping figures to scripts, datasets, cache links, etc. In principle it doesn't matter what that label is called, so if there are two labels in one figure environment, we could just map all the figure attributes to the first label and ignore the second one. We already kind of do that [here](https://github.com/showyourwork/showyourwork/blob/0c065b2dc5f74b9612ab064d6674b91e206404ce/showyourwork/workflow/scripts/preprocess.py#L329) -- so, like you said, it's really just a matter of getting rid of that exception.

The second issue is that the way we display margin icons next to figures is by hacking the `showkeys` package, which is used to display the `\label` corresponding to various manuscript elements in the margin. People use this during writing to, e.g., easily identify which equation label corresponds to a given equation number by just glancing at the PDF. `showyourwork` [overrides this functionality](https://github.com/showyourwork/showyourwork/blob/0c065b2dc5f74b9612ab064d6674b91e206404ce/showyourwork/workflow/resources/styles/build.tex#L197) to display the associated icons instead of just the label name (and only for figures, currently).

Again, in principle at least, this shouldn't be too much of a problem. One of the labels for the figure in your case won't have any associated icons, so [these if statements](https://github.com/showyourwork/showyourwork/blob/0c065b2dc5f74b9612ab064d6674b91e206404ce/showyourwork/workflow/resources/styles/build.tex#L201) will evaluate to false and display nothing. But I don't know how `showkeys` itself behaves when elements have multiple labels, so we'd have to test that.

So, if you're willing @dfm, can you remove the exception in your fork, build the PDF with the Annual Reviews document class, and let me know if the margin icons display correctly?

**Comment by dfm** [comment]
Great - thanks! How do I switch to using a fork? I see the showyourwork version number listed in a few places, but I couldn't quite figure out the workflow.

**Comment by rodluger** [comment]
Ha, great question. It's not implemented! But there's a workaround -- see [here](https://github.com/showyourwork/showyourwork/blob/main/showyourwork/cli/conda_env.py#L84-L104). In `showyourwork.yml`, you can specify the `showyourwork` version as a proper version number, a commit SHA, or a local path to the package. So locally it's easy -- just specify the version as the path (both relative and absolute should work) to your fork. On GitHub Actions, you'll have to manually check out the fork in the `build.yml` workflow, but I imagine you won't have any trouble with that.

Alternatively, you could add a case to those if statements linked above to check for a fork and install it directly from GitHub, and give me a PR....

**Comment by rodluger** [comment]
(BTW, the version of `showyourwork` that spins up the workflow is whatever version you have installed locally. On GitHub actions, it's always the latest version of the package on PyPI, and that can't be changed, currently. But it shouldn't matter -- the only thing that version is doing is to create and activate an isolated conda environment with the user-requested `showyourwork` version, and spin up a new instance of `showyourwork` in there. So as long as you're not changing anything in the `showyourwork/cli` subfolder, it shouldn't matter).
