### ISSUE TITLE
Should we just remove the packaged classfiles?

### ISSUE THREAD

**Issue by dfm** [showyourwork/showyourwork#154]

**Comment by rodluger** [comment]
For context, there's no good reason to provide the classfiles (like `aastex`, `mnras`, etc.) Users should include necessary classfiles as committed files within the `src/tex` directory. This way, we won't have to maintain these third-party files, which would become intractable anyways if we start getting people from other disciplines to use `showyourwork`.

This also fixes the issue raised in #152: if the user provides their own classfile like ``aastex``, we currently overwrite it with the packaged version on build.

The only thing in the way of fixing this issue ASAP is that there are a few bugs in ``aastex`` that I fixed in the ``showyourwork``-provided version. The main one is an inconsistent naming of the ``orcid-ID.png`` icon, which at one point during the development of the code was causing all sorts of issues. I'll look into this.
