### ISSUE TITLE
LaTeX Error: Float(s) lost when using MNRAS style

### ISSUE THREAD

**Issue by TobiBu** [showyourwork/showyourwork#224]
Hi,
I am trying to use showyourwork with the MNRAS template but I fail to get it to compile and always receive the error

`LaTeX Error: Float(s) lost.`

which seems to be connected to the showyourwork-logo.pdf according to the log.

did anyone made showyourwork compile with the morass template?

**Comment by rodluger** [comment]
Hi @TobiBu, can you send me the full build logs (in `.showyourwork/logs`) or (better yet) point me to the actual repository so I can poke around?

**Comment by TobiBu** [comment]
Hi @rodluger,

the repo is located here: https://github.com/TobiBu/GSE_merger

**Comment by rodluger** [comment]
The error was not due to the showyourwork logo, but to the GitHub icon placed in the margin of the abstract. I don't fully understand why this was happening, so I'm suggesting you temporarily override the code that produces that icon (see https://github.com/TobiBu/GSE_merger/pull/1). I'm going to keep this issue open so I can track down the actual cause of the error when I have time (prob only next week).

**Comment by dfm** [comment]
The same issue happened with the annual reviews class. I fixed it by making the icon inline. Perhaps we should have a config setting for that?

**Comment by TobiBu** [comment]
I see. Thanks.
At which place in the code do I find where the icon is put in?

Actually, I like the inline version. A config setting seems a code option.

**Comment by rodluger** [comment]
The new release (`0.4.0`, next couple days) will fix this, as we're doing away with the abstract icon entirely in favor of a stamp-like mark in the margin linking to the paper repository.
