### ISSUE TITLE
Problems with arxiv submission

### ISSUE THREAD

**Issue by bruce-edelman** [showyourwork/showyourwork#227]
Hi, I have **thoroughly** enjoyed using showyourwork on my latest project. It has been incredibly useful and I cannot imagine going back to my old ways of writing papers!

I have recently been trying to submit a paper to arxiv and having trouble getting it to build correctly through their automated process. I am using version 0.4.0 and everything works fine without errors or warnings in the log files locally. After creating a tarball and uploading to arxiv I get this error in the *second* `pdflatex` call every time. 
```
(/texlive/2020/texmf-dist/tex/latex/fontawesome5/ufontawesomefree0.fd)
(/texlive/2020/texmf-dist/tex/latex/fontawesome5/ufontawesomebrands0.fd)
[3] [4
! pdfTeX error (ext4): \pdfendlink ended up in different nesting level than \pd
fstartlink.
\AtBegShi@Output ...ipout \box \AtBeginShipoutBox
\fi \fi
l.44

! ==> Fatal error occurred, no output PDF file produced!
Transcript written on ms.log.

[verbose]: pdflatex 'ms.tex' failed.
```

When I remove the `showyourwork.tex` file and everything builds correctly through arxiv's machine -- but of course without the lovely showyourwork stamp and margin icon buttons which I would really love to have included on the pdf that is on arxiv. I also checked that I can successfully build the paper from the arxiv tarball locally with `pdflatex` and can just fine to add to the weirdness. 

Is this some sort of user error on my behalf and/or something that you have seen before? Thanks again for the amazing package and time reading this!

**Comment by rodluger** [comment]
Thanks for catching this! The error is probably due to [these lines](https://github.com/showyourwork/showyourwork/blob/8f34de9770fddaa4111ce95e4405f9fcfa958fea/showyourwork/workflow/resources/styles/build.tex#L114-L119) in the `showyourwork` TeX package, where we use the `AddToShipoutPictureBG` command in the `eso-pic` package to add the stamp to the first page. That probably calls `AtBeginShipoutBox`behind the scenes. I imagine arXiv may be doing something similar to add the watermark in the margin, therefore leading to that error? Just a guess.

I'll try to come up with a workaround. In the time being, you can probably get it to work by setting

```
stamp:
  enabled: false
```

in `showyourwork.yml`. This will disable the stamp but allow you to keep all the other features.

**Comment by rodluger** [comment]
@bruce-edelman just a quick update. I can reproduce your issue with the submission. But if I comment out all of the `\input` commands (for `macros.tex` and all of the sections), the arXiv submission gets processed just fine. (It also works just fine for one of the articles that I'm currently working on). Would you mind doing a little more debugging on your end to isolate the issue? I don't have time this week to look into your paper in detail, but I bet you can figure it out if you progressively uncomment those `\inputs` one by one...

**Comment by dfm** [comment]
Closing as stale, but please feel free to reopen with more info!
