### ISSUE TITLE
`\variable` has space following it

### ISSUE THREAD

**Issue by arm61** [showyourwork/showyourwork#286]
Using the `\variable` command results in a space after it, this is a problem I also found with standard LaTeX `\input`, but unlike with `\input` using `\unskip` does not remove the space. It is a problem if you have a `\variable` followed by (for example) a comma (see image). 

<img width="594" alt="Screenshot 2023-02-13 at 08 09 58" src="https://user-images.githubusercontent.com/15774281/218393308-a2935e53-756b-452f-8763-877aa1f083fc.png">

**Comment by arm61** [comment]
I am happy to look at fixing it at some point this week.

**Comment by dfm** [comment]
Interesting! I would have expected `\variable` to be identical to `\input` by the time it's compiled, but I never know what to expect with TeX 😀

If you can figure out how to get the behavior you want, let's do that! But if not, perhaps we can document a workaround somewhere. The workaround I would use would be to use `\variable` to define a new LaTeX macro that you can then use where you need it in the text.

The right place to look is probably in `showyourwork/workflow/resources/styles/build.tex` (on my phone so that path is only approximate 😀) because that's the style file that's used when compiling.

**Comment by arm61** [comment]
Looks like there is already an `\unskip` in there, so I guess that it is TeX adding another space as part of the `\newcommand`?
https://github.com/showyourwork/showyourwork/blob/4dd722a5f9474a9de656573aebdebaa3fc91ecd9/showyourwork/workflow/resources/styles/build.tex#L213

**Comment by dfm** [comment]
Good point! Or maybe it's related to the `\label` in there?

**Comment by arm61** [comment]
Good point, I looked past the label, but what is the purpose of it?

**Comment by dfm** [comment]
I assume the point of the label is to support having margin icons for that variable, but I'm not entirely sure! Let's dig into this a little bit.

**Comment by arm61** [comment]
Turned out to be a really easy fix.
