### ISSUE TITLE
Overleaf passwords containing "*"

### ISSUE THREAD

**Issue by ciskakemper** [showyourwork/showyourwork#323]
Overleaf passwords with a * in it are not always allowed to be defined as an environment variable. It should probably included into the documentation that setting environment variables only works if certain characters, including *, are not part of the overleaf password.

**Comment by dfm** [comment]
I _think_ that environment variables can include a `*` (at least in my environment), as long as the variable value is quoted, e.g.:

```bash
export OVERLEAF_PASSWORD="something_with_a_*"
```

It's totally possible that we don't use such environment variables properly in our Overleaf integration. Did the issues occur when you were setting the variable, or when you were using it within `showyourwork`? If the former, perhaps we could add a note to the documentation. Otherwise, there's probably an issue that we need to fix internally. Thanks!

**Comment by ciskakemper** [comment]
When I was setting the variable.

**Comment by dfm** [comment]
Got it - well the trick of quoting the value works fine on my end. Does that work for you?

**Comment by ciskakemper** [comment]
Yes, it now works for me too. I could swear I tried using the quotation marks before, and that it didn't work, but my memory is failing here, it seems. Ok, this can be closed then I guess, it's a non-issue.

**Comment by dfm** [comment]
No worries at all! Let's keep this open for now because I want to double check how we use the password in our integration to make sure it is safe from this issue, and it would be worth adding a clear statement about this to the docs.

**Comment by HealthyPear** [comment]
I'll close this issue since Overleaf moved to tokens (see #465).
