### ISSUE TITLE
Sandbox zenodo cache repos have disappeared...

### ISSUE THREAD

**Issue by mkenworthy** [showyourwork/showyourwork#336]
As of 28 march, syw! is complaining about lack of access to Zenodo cached repos.... logging into my Zenodo, I no longer see my cached Zenodo repos, and I can only find the data repos on sandbox Zenodo if I search for them. Is anyone else experiencing this, or has it happened before to anyone?

**Comment by dfm** [comment]
Hi @mkenworthy — [As described in the showyourwork docs](https://show-your.work/en/latest/zenodo/#setting-up-zenodo-integration), Zenodo _sandbox_ records should always be considered temporary because Zenodo frequently wipes those listings. If you need a longer term caching option, you should use Zenodo (not sandbox).
