### ISSUE TITLE
Which is a good workflow to mix the repository created by ShowYourWork with the repo generated by PkgTemplates.jl ?

### ISSUE THREAD

**Issue by martinmestre** [showyourwork/showyourwork#374]
With PkgTemplates.jl I generate the project repo to run Julia code and  ShowYourWork creates its own repo with a script directory. How could I have both simultaneously?

**Comment by dfm** [comment]
Pinging @MilesCranmer who might be able to answer!

**Comment by martinmestre** [comment]
Thanks!  
A workaround I have thought of is that in the paper repo built by ShowYourWork, just put simple scripts that call my package repo placed in another place (e.g. ".julia/dev/" directory). Maybe this is the suggested workflow?

**Comment by MilesCranmer** [comment]
PkgTemplates.jl is more for generating a Julia package/library, rather than generating a paper repository or documentation like showyourwork is used for. What use-case do you have?

I guess you could just copy all the files over from repo to the other? Are there any specific conflicts you are seeing?

**Comment by martinmestre** [comment]
Thanks! I am seeing no conflicts in your suggestion. I will have the package/library isolated from the paper repository.
