### ISSUE TITLE
 snakemake 7.15.2 does not work with pulp 2.8.0

### ISSUE THREAD

**Issue by thomasckng** [showyourwork/showyourwork#430]
showyourwork install snakemake 7.15.2 currently and it calls `pulp.list_solvers` in snakemake/__init__.py line 1471 `get_argument_parser`. That function is changed to `pulp.listSolvers` in pulp 2.8.0. Github action install pulp 2.8.0 now, as the requirement is just `pulp>=2.0`. Newer version of snakemake is compatible with pulp 2.8.0. Maybe we can change the dependency to a newer version of snakemake or restrict the version of pulp?

**Comment by dfm** [comment]
Thanks! I see this behavior too. I think the preferred approach would be to add an upper limit on the version of pulp here:

https://github.com/showyourwork/showyourwork/blob/8e3450784adf67ebc0472903d7d39c0ff209dec8/pyproject.toml#L26

Because there are compatibility issues with the most recent versions of snakemake (ref: https://github.com/showyourwork/showyourwork/pull/264).

Would you be able to open a PR? Thanks!

**Comment by dfm** [comment]
Closed in #433. Thanks @thomasckng!
