### ISSUE TITLE
build not working, reporting: Overleaf now only supports Git authentication tokens to access git

### ISSUE THREAD

**Issue by mkenworthy** [showyourwork/showyourwork#465]
As of today, showyourwork build with an Overleaf password and login stopped working: when I try to build, I get this message:

```
remote: Overleaf now only supports Git authentication tokens to access git. See: https://www.overleaf.com/learn/how-to/Git_integration_authentication_tokens
fatal: unable to access 'https://git.overleaf.com/64b800970dbbbxxxxxxxxxxxx/': The requested URL returned error: 403
```
So, my feature request would be to have syw work with Git authentication tokens.

**Comment by thomasckng** [comment]
I had the same problem. Some additional info from Overleaf.
https://www.overleaf.com/learn/how-to/Git_integration_authentication_tokens

**Comment by thomasckng** [comment]
This should work. You may need to make a token from Overleaf and put it in your repo as secret. Same for local build.

**Comment by thomasckng** [comment]
The `env` variable in `.github/workflows/build.yml` and `github/workflows/build-pull-request.yml` need to be changed as well.

**Comment by HealthyPear** [comment]
I have a question about this: if I am collaborating with other people on a project, does this mean I have to share my token with them since all authors would need to define the correspondent environment variable?

The scope of an Overleaf token as far as I know it's the account of the user not a single project.

I see this
https://www.overleaf.com/learn/how-to/Git_integration_authentication_tokens#How_to_work_with_collaborators
but it is not clear to me how it reconciles with the GitHub secret token.

**Comment by thomasckng** [comment]
I think this depends on different situations.

The simplest case is they just modify your manuscript on overleaf. You just need to share with them your Overleaf project. They don't need to care about anything related to showyourwork. In this case, you just need to put your own Overleaf token in the GitHub secret and your local environment. It will work for both local and remote builds. You will need to handle all the figure-generation scripts yourself.

If all your collaborators know how to use showyourwork, you don't need overleaf integration. Everyone can commit to the git repo themselves.

The more complicated case would be some of your collaborators want to use showyourwork and some need Overleaf. In that case, you still just need to put your own Overleaf token in the GitHub secret. The remote build will work. For your collaborators to build locally. They will need to declare their own Overleaf token in their local environment. If they don't even want to build it locally, they can just commit and push changes to the figure scripts to GitHub directly and wait for the remote build to run.

One important thing is as long as you activated Overleaf integration, you need to make your changes for the `tex` and `bib` on Overleaf. If you directly make your changes in the git repo instead of via Overleaf, problems mentioned in [here](https://show-your.work/en/latest/overleaf/#managing-conflicts) will occur.
