### ISSUE TITLE
syw still looking for OVERLEAF_EMAIL and OVERLEAF_PASSWORD, despite env OVERLEAF_TOKEN being set; doesn't pull files

### ISSUE THREAD

**Issue by outs1der** [showyourwork/showyourwork#494]
I made changes to my integrated overleaf repo, and wanted to pull them into the local version; I've set the environment variable OVERLEAF_TOKEN but get the following 

>  $ showyourwork build                    
Fetching Overleaf repo...
Overleaf credentials `OVERLEAF_EMAIL` and/or `OVERLEAF_PASSWORD` not found. These should be set as both environment variables and GitHub repository secrets.
Building the workflow graph...
Copying the article PDF...
Copying the article synctex...
Fetching Overleaf repo...
Overleaf credentials `OVERLEAF_EMAIL` and/or `OVERLEAF_PASSWORD` not found. These should be set as both environment variables and GitHub repository secrets.
Done!

And it doesn't pull the updated .tex and .bib files. (despite it reporting having done so, twice!)

If I instead set OVERLEAF_EMAIL and OVERLEAF_PASSWORD, I get the error reported in issue #465

**Comment by HealthyPear** [comment]
The fix is not yet part of a released version of showyourwork, so you need to install it from a cloned repository for the moment:

1. `git clone https://github.com/showyourwork/showyourwork.git`
2. `pip install showyourwork`

Thank you for reporting this, the main cause is a shortcoming in our documentation, it needs to be updated.
Also I just realized that the documentation page for the github action is broken...

**Comment by HealthyPear** [comment]
Again, let me know if this (temporary!) solution fixes your problem.

**Comment by outs1der** [comment]
yep that fixed things, thanks again. I think maybe for the installation I actually need to 
1. `cd showyourwork`
2. `pip install .`

but either way I now have the new 0.4.4.dev67 version. I do now have a sync problem

> Local file changed since the last Overleaf sync: ms.tex. Refusing to overwrite with Overleaf version. Please see the docs for details on how to resolve this.

but I think I can manage that
