### ISSUE TITLE
Passing builds on branches still point to main-xx

### ISSUE THREAD

**Issue by katiebreivik** [showyourwork/showyourwork#97]
We found this because we are working on a branch that is not main (e.g. [this branch here](https://github.com/kazewong/BackPop/tree/Rework)).

It appears to be totally fine to just update the README by hand (i.e. [in this commit](https://github.com/kazewong/BackPop/commit/05ca198a14fbd3457ba51272b33ca988acdd4619)), but I think this can probably be fixed by editing the cookiecutter repo to not point to main-pdf always (as I think is done for the badges [here](https://github.com/showyourwork/showyourwork/tree/main/showyourwork/cookiecutter-showyourwork/%7B%7B%20cookiecutter.repo%20%7D%7D))

**Comment by rodluger** [comment]
Right. It's not as simple as fixing the cookiecutter, since any time you create a new branch on GitHub (or just in git), you base it off an existing branch, so it will always get created with the wrong badge in the README initially. Showyourwork has no say in any of this!

One hack could be to create a new GitHub Actions workflow that gets triggered whenever a branch is created and replaces any references to a branch in the README links with the new branch name.

**Comment by katiebreivik** [comment]
ahhh Got it. I just figured this out the hard way because I didn't see your response. I should have some time to look into creating a Github Actions workflow on a couple-ish week long timescale. But if you want to close the issue, I'm happy with that.

**Comment by rodluger** [comment]
Happy to help with it too. Let me know.

**Comment by dfm** [comment]
I'm going to close this as out of scope for showyourwork, since this is really a more general quality of life improvement that would be more broadly applicable.
